server.port=8082
spring.application.name=ms-pagos

# --- Configuración de MySQL ---
spring.datasource.url=jdbc:mysql://localhost:3306/smartlogix_pagos?createDatabaseIfNotExist=true&serverTimezone=America/Santiago
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# --- Credenciales Sandbox (De prueba) ---
pasarelas.webpay.commerce-code=597055555532
pasarelas.webpay.api-key=579B532A7440BB0C9079DED94D31EA1615BACEB56610332264630D42D0A36B1C
pasarelas.mercadopago.access-token=TEST-tu-token-de-prueba-aqui
pasarelas.khipu.receiver-id=tu-id-de-prueba
pasarelas.khipu.secret=tu-secreto-de-prueba

# --- Configuración del Circuit Breaker (Resilience4j) ---
management.health.circuitbreakers.enabled=true
management.endpoints.web.exposure.include=health

# --- Configuración de Instancia: Webpay ---
resilience4j.circuitbreaker.instances.webpayCB.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.webpayCB.slidingWindowSize=10
resilience4j.circuitbreaker.instances.webpayCB.failureRateThreshold=50
resilience4j.circuitbreaker.instances.webpayCB.waitDurationInOpenState=10s

# --- Configuración de Instancia: MercadoPago ---
resilience4j.circuitbreaker.instances.mercadopagoCB.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.mercadopagoCB.slidingWindowSize=10
resilience4j.circuitbreaker.instances.mercadopagoCB.failureRateThreshold=50
resilience4j.circuitbreaker.instances.mercadopagoCB.waitDurationInOpenState=10s

# --- Configuración de Instancia: Khipu ---
resilience4j.circuitbreaker.instances.khipuCB.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.khipuCB.slidingWindowSize=10
resilience4j.circuitbreaker.instances.khipuCB.failureRateThreshold=50
resilience4j.circuitbreaker.instances.khipuCB.waitDurationInOpenState=10s


# ==========================================
# CONFIGURACIÓN DE REINTENTOS PARA EL SII
# ==========================================
# Número máximo de intentos (1 intento original + 4 reintentos)
resilience4j.retry.instances.siiRetry.max-attempts=5

# Tiempo de espera entre cada intento (2 segundos)
# Esto da un total aproximado de 10 segundos de tolerancia
resilience4j.retry.instances.siiRetry.wait-duration=2s


# ==========================================
# CONFIGURACIÓN DE ALERTAS (SLACK)
# ==========================================
# IMPORTANTE: Nunca subir la URL real a GitHub. 
slack.webhook.url=URL_SECRETA_REEMPLAZAR_EN_LOCAL
